steps:
  - label: Ubuntu build
    command:
      - ./.ci/ubuntu.sh
    agents:
      queue: ubuntu
  - label: OSX build
    command:
      - ./.ci/osx.sh
    agents:
      queue: osx
  - label: FreeBSD build
    command:
      - ./.ci/freebsd.sh
    agents:
      queue: freebsd