steps:
  - command: |
        echo --- Setup the Nix Package Manager
        nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs && nix-channel --update
        if [[ $? -ne 0 ]]; then
          echo ^^^ +++
        fi

        echo --- Restore Cached Nix Packages
        test -d /nixcache/store && cp -pur /nixcache/store /nix/ && \
          test -d /nixcache/var && cp -pur /nixcache/var /nix/
        if [[ $? -ne 0 ]]; then
          echo ^^^ +++
        fi

        nix-shell --run bash <<'NIXSH'
          echo --- Build spook
          make
          if [[ $? -ne 0 ]]; then
            echo ^^^ +++
          fi

          echo +++ Lint
          make lint

          echo +++ Test
          make test
        NIXSH

        echo --- Save Nix Cache
        cp -pur /nix/* /nixcache/
        echo ^^^ +++

    timeout: 600
    plugins:
      - docker#v3.0.1:
          image: "nixorg/nix:latest"
          volumes:
            - "/var/lib/buildkite/nixcache:/nixcache"