steps:
  - label: Linux build
    command:
      - ./.ci/linux.sh
    agents:
      queue: linux
  - label: OSX build
    command:
      - ./.ci/osx.sh
    agents:
      queue: osx
  - label: FreeBSD build
    command:
      - ./.ci/freebsd.sh
    agents:
      queue: freebsd